site_name: Secronomicón
site_description: 'Libro de notas donde encontrarás cada truco/técnica/guía de hacking que he aprendido y recolectado de CTFS, aplicaciones reales, lectura de writeups y noticias.'
theme:
  name: material
  language: es
  palette: 
    - scheme: slate
  features:
    - content.code.copy
    - navigation.top
    - navigation.sections

extra_css:
  - extra.css

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
